module PTP
{

  enum MsgType
  {
    SYNC,
    FOLLOWUP,
    DELAYREQUEST,
    DELAYRESPONSE
  };

  struct Msg
  {
    MsgType type;         
    unsigned long long value;     
  };

};